# Generated by Django 2.0.5 on 2018-05-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveddonor',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
