# Generated by Django 2.0.5 on 2018-05-28 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_saveddonor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddonor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donors', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
