# Generated by Django 2.0.5 on 2018-05-29 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_auto_20180528_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddonor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donors', to=settings.AUTH_USER_MODEL),
        ),
    ]
