# Generated by Django 2.0.5 on 2018-05-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_auto_20180529_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddonor',
            name='percent_dem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
