# Generated by Django 2.0.5 on 2018-05-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_saveddonor_percent_dem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddonor',
            name='committees',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
